# mall-product 数据库配置 - 放入Nacos配置中心
# Data ID: mall-product.yml
# Group: DEFAULT_GROUP
# 描述: 商品服务的MySQL数据库连接配置

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: your-database-password

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: xyh.dp.mall.product.entity
